---
- hosts: development
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
    - vars/main.yml
  gather_facts: yes
  roles:
    - role: geerlingguy.firewall
    - role: geerlingguy.ntp
    - role: geerlingguy.mysql
    - role: geerlingguy.apache
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: dev_tools
    - role: tool_server
    - role: setup_coral





